{% set name = "asdf-wcs-schemas" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asdf_wcs_schemas-{{ version }}.tar.gz
  sha256: c0bb44b8a5f16e2e23b028bcf4360729f5047a8d19063f1c8d817590d0b308b4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - asdf-standard >=1.1.0
    - asdf-transform-schemas >=0.5.0
    - asdf-coordinates-schemas >=0.3.0
    - python >={{ python_min }}

test:
  imports:
    - asdf_wcs_schemas
    - asdf_wcs_schemas.resources
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asdf-format/asdf-wcs-schemas
  summary: ASDF WCS Schemas
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwcraig
    - braingram 
    - jhunkeler
    - nden
