{% set name = "asdf-wcs-schemas" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_wcs_schemas-{{ version }}.tar.gz
  sha256: 0a13420a5d1996cf3025e43e83d7beeac0917d9e58a9eeec4ef83edcdfe8c742

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - asdf-standard >=1.0.1
    - asdf-transform-schemas >=0.3.0
    - asdf-unit-schemas >= 0.1.0
    - importlib_resources >=3
    - python >=3.8

test:
  imports:
    - asdf_wcs_schemas
    - asdf_wcs_schemas.resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asdf-format/asdf-wcs-schemas
  summary: ASDF WCS Schemas
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwcraig
    - WilliamJamieson
